name: EssentialsZ
version: ${project.version}
main: me.darkwinged.EssentialsZ.Main
authors: [darkwinged, Yovez]
softdepend: [PlaceholderAPI, Vault, ProtocolLib, EssentialsZSpawn]
depend: [EssentialsZAPI]
load: STARTUP
loadbefore: [Vault]
commands:
  economy:
    aliases:
      - econ
      - eco
  balance:
    aliases:
      - bal
      - money
      - bank
      - wallet
  pay:
  withdraw:
    aliases:
      - with
      - wd
  pouches:
  autosell:
  sell:
  sellhand:

  staffchat:
    aliases:
      - sc
  clearchat:
    aliases:
      - cc
  broadcast:
    aliases:
      - bc
      - aleart
  mutechat:
  motd:
  sudo:

  tp:
  tphere:
  hub:
  rtp:
    aliases:
      - wild
  top:
  setwarp:
  delwarp:
  warp:
  warps:
  sethome:
  delhome:
  home:
  homes:
  back:

  ping:
  essentials:
    aliases:
      - ess
      - essentialsz
  hat:
  gamemode:
    aliases:
      - gm
  gma:
  gmc:
  gms:
  gmsp:
  invsee:
  vanish:
    aliases:
      - v
  reward:
    aliases:
      - daily
  repair:
  world:
  delworld:
  enderchest:
    aliases:
      - ec
  disposal:
    aliases:
      - trash
      - bin
      - garbage
  craft:
  kill:
  god:
  heal:
  fly:
  feed:
  smite:
  filltnt:
  cps: