############################################################
# +------------------------------------------------------+ #
# |                 EssentialsZ Friends                  | #
# +------------------------------------------------------+ #
############################################################

Request Time: 120 # seconds.