name: EssentialsZ
version: ${project.version}
main: me.darkwinged.essentialsz.Main
authors: [darkwinged, Yovez]
softdepend: [PlaceholderAPI, Vault, ProtocolLib, EssentialsZSpawn]
depend: [EssentialsZAPI]
load: STARTUP
loadbefore: [Vault]
commands:
  reload:
    description: Reloads all configuation files.

  economy:
    description: Manage everyones balance.
    aliases:
      - econ
      - eco
  balance:
    description: How much you have in your account.
    aliases:
      - bal
      - money
      - bank
      - wallet
  pay:
    description: Allows users to transfer money


  day:
    description: Turns the time in a specific world to day.
  night:
    description: Turns the time in a specific world to night.

  condense:
    description: Takes all valuables and turns them into blocks.








  withdraw:
    aliases:
      - with
      - wd
  pouches:
  autosell:
  sell:
  sellhand:

  staffchat:
    aliases:
      - sc
  clearchat:
    aliases:
      - cc
  broadcast:
    aliases:
      - bc
      - aleart
  mutechat:
  motd:
  sudo:

  tp:
  tphere:
  hub:
  rtp:
    aliases:
      - wild
  top:
  setwarp:
  delwarp:
  warp:
  warps:
  sethome:
  delhome:
  home:
  homes:
  back:

  ping:
  essentials:
    aliases:
      - ess
      - essentialsz
  hat:
  gamemode:
    aliases:
      - gm
  gma:
  gmc:
  gms:
  gmsp:
  invsee:
  vanish:
    aliases:
      - v
  repair:
  world:
  delworld:
  enderchest:
    aliases:
      - ec
  disposal:
    aliases:
      - trash
      - bin
      - garbage
  craft:
  kill:
  god:
  heal:
  fly:
  feed:
  smite:
  cps:
  weather:
  pweather:
  sun:
  storm:
  time:
  ptime:
