name: EssentialsZ
version: ${project.version}
main: me.darkwinged.essentialsz.Main
authors: [darkwinged, Yovez]
softdepend: [PlaceholderAPI, Vault, ProtocolLib, EssentialsZSpawn]
depend: [EssentialsZAPI]
load: STARTUP
loadbefore: [Vault]
commands:
  reload:
    description: Reloads all configuation files.

  economy:
    description: Manage everyones balance.
    aliases:
      - econ
      - eco
  balance:
    description: How much you have in your account.
    aliases:
      - bal
      - money
      - bank
      - wallet
  pay:
    description: Allows players to transfer money.
  withdraw:
    description: Allows players to withdraw money.
    aliases:
      - with
      - wd
  sell:
    description: Allows players to sell items inside of their inventory.
    aliases:
      - sellall
  sellhand:
    description: Sells all of one type of item in a players inventory.
  autosell:
    description: Allows players to automatically sell items.
  chestsell:
    description: Allows players to sell all items inside of a chest.

  sellwand:
    description: Gives a player a wans to sell items.

  day:
    description: Turns the time in a specific world to day.
  night:
    description: Turns the time in a specific world to night.
  condense:
    description: Takes all valuables and turns them into blocks.
  craft:
    description: Opens a workbench.
  suicide:
    description: This is useful in desprite situations.
  hat:
    description: Allows players to wear blocks/items on their head.









  pouches:

  staffchat:
    aliases:
      - sc
  clearchat:
    aliases:
      - cc
  broadcast:
    aliases:
      - bc
      - aleart
  mutechat:
  motd:
  sudo:

  tp:
  tpoffline:
  tphere:
  hub:
  rtp:
    aliases:
      - wild
  top:
  setwarp:
  delwarp:
  warp:
  warps:
  sethome:
  delhome:
  home:
  homes:
  back:

  ping:
  essentials:
    aliases:
      - ess
      - essentialsz
  gamemode:
    aliases:
      - gm
  gma:
  gmc:
  gms:
  gmsp:
  invsee:
  vanish:
    aliases:
      - v
  repair:
  world:
  delworld:
  enderchest:
    aliases:
      - ec
  disposal:
    aliases:
      - trash
      - bin
      - garbage
  kill:
  god:
  heal:
  fly:
  feed:
  smite:
  cps:
  weather:
  pweather:
  sun:
  storm:
  time:
  ptime:
